
spring:
  main: 
    allow-bean-definition-overriding: true

server:
  port: 9094

dubbo:
  application:
    name: consumer-service-app1
  registry:
    address: zookeeper://127.0.0.1:2181
    # 设置临时节点
    dynamic: false
  consumer: 
    timeout: 3000
  # 实现配置中心集中化配置
#  config-center:
#    namespace: consumer-service-app1
#    address: zookeeper://127.0.0.1:2181

