spring:
  main:
    allow-bean-definition-overriding: true

dubbo:
  application:
    name: service-app1
  registry:
    # dynamic  默认 true 持久节点     false  临时节点
    address: zookeeper://127.0.0.1:2181?dynamic=false
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.example.study.dubbo.provider
server:
  port: 9093
